import { get_comment } from "./api.mjs";
import { addImage, deleteImage, addComment, deleteComment, get_next_image, get_previous_image, get_latest_image, } from "/js/api.mjs";


//localStorage.clear();
loadLatestImage();

//This snippet of code is copied and modified from the starter code of lab 2

document
    .getElementById("create_image_form")
    .addEventListener("submit", function (e) {
        // prevent from refreshing the page on submit
        e.preventDefault();
        // read form elements



        //Fetch the information input by the user
        const url = document.getElementById("url").value;
        const author = document.getElementById("name").value;
        const title = document.getElementById("title").value;

        console.log(url, author, title);

        //Store info
        addImage(title, author, url);

        // clean form
        document.getElementById("create_image_form").reset();

        //load the image
        loadLatestImage();

    });



const button = document.getElementById("hide");
const fields = document.getElementById("fields");


//This snippet of code is generated by https://www.w3schools.com/css/css3_animations.asp
button.addEventListener("click", () => {
    fields.classList.toggle("show");
    button.textContent = fields.classList.contains("show") ? "Hide" : "Expand";
});


function loadNextImage(imageId) {
    let image = get_next_image(imageId);
    if (image == null) {
        return;
    }
    loadImage(image);
}

function loadPreviousImage(imageId) {
    let image = get_previous_image(imageId);
    if (!image) {
        return;
    }
    loadImage(image);
}

function loadLatestImage() {
    let image = get_latest_image();

    if (image == null) {
        return;
    }
    loadImage(image);
}

function loadLatestComments(imageId) {
    document.getElementById("messages").innerHTML = ``;
    let comments = get_comment(imageId);

    if (!comments) {
        return;
    }

    if(comments.length == 0){
        return;
    }

    loadComments(comments, comments.length - 1);
}

function loadPreviousComments(comments, start) {
    if(start == comments.length - 1){
        return;
    }
    document.getElementById("messages").innerHTML = ``;
    if (start + 20 <= comments.length - 1) {
        loadComments(comments, start + 20);
    }
    else {
        loadComments(comments, comments.length - 1);
    }
}

function loadNextComments(comments, start) {
    
    if(start == 0){
        return;
    }
    document.getElementById("messages").innerHTML = ``;
    loadComments(comments, start);
}

function loadComments(comments, start) {
    let position = 0;
    let counter = 0
    let comment_sec = document.getElementById("messages");
    for (let i = start; i >= 0; i--) {
        position = i;
        console.log(position);
        //If more than 10 comments are loaded, stop loading and create the buttons for nevigating
        if (counter == 10) {
            const nevi = document.createElement("div");
            nevi.innerHTML = `
            <button type="button" class="btn" id="forward">◀</button>
           
            <button type="button" class="btn" id="backward">▶</button>

            <span>${comments.length - start} - ${comments.length - start + counter - 1} / ${comments.length}</span>
            `;

            

            comment_sec.append(nevi);

            document.getElementById("forward").addEventListener("click", function (e) {
                loadPreviousComments(comments, i);
            });

            document.getElementById("backward").addEventListener("click", function (e) {
                loadNextComments(comments, i);
            });

            return;

        }
    
        const elmt = document.createElement("div")
        const date = new Date(comments[i].date);
        const time = date.toLocaleString();
        elmt.className = "message";
        elmt.innerHTML = `
        <div class="message_user">
            <div class="message_username">${comments[i].author}</div>
            <div class="message_username">Posted on: ${time}</div>
        </div>
        <div class = "message_user"">
            <div class="message_content">${comments[i].content}</div>
            <div class="delete-icon icon" id="delete${i}"></div>
        </div>
    `;
        comment_sec.append(elmt);

        document.getElementById("delete" + i).addEventListener("click", function (e) {
            console.log(i + comments[i].imageId + comments[i].commentId);
            deleteComment(comments[i].commentId, comments[i].imageId);
            loadLatestComments(comments[i].imageId);
        });

        counter++;
    }
    const nevi = document.createElement("div");
    nevi.innerHTML = `
            <button type="button" class="btn" id="forward">◀</button>
           
            <button type="button" class="btn" id="backward">▶</button>

            <span>${comments.length - start} - ${comments.length -  position} / ${comments.length}</span>
            `;



    comment_sec.append(nevi);

    document.getElementById("forward").addEventListener("click", function (e) {
        loadPreviousComments(comments, position);
    });

    document.getElementById("backward").addEventListener("click", function (e) {
        loadNextComments(comments, position);
    });
}
function loadImage(image) {
    document.getElementById("image_sec").innerHTML = "";
    document.getElementById("messages").innerHTML = ``;
    // create a new message element
    const elmt = document.createElement("div");
    elmt.className = "image_container";
    const date = new Date(image.date);
    const time = date.toLocaleString();
    elmt.innerHTML = `
        <div class="img_title"> ${image.title} by ${image.author} <br> posted on: ${time}</div>
        
        <div class="image">
            <button type="button" class="btn" id="left">◀</button>
            <img src="${image.url}" alt="User image" width="300" height="300">
            <button type="button" class="btn" id="right">▶</button>
        </div> 

        <button type="button" class="dele_btn" id="delete">Delete this image</button>

        <form id="comment_form">

            <input type="text" id="comment_name" class="comment" placeholder="Enter your name"
                    required />

            <input type="text" id="comment" class="comment" placeholder="Enter your comment" required />

            <button type="button" class="btn" id="add_comment">Add comment</button>

         </form> 

    `;
    // add this element to the document
    document.getElementById("image_sec").append(elmt);

    document.getElementById("left").addEventListener("click", function (e) {
        loadPreviousImage(image.imageId);
    })

    document.getElementById("right").addEventListener("click", function (e) {
        loadNextImage(image.imageId);
    })

    document.getElementById("delete").addEventListener("click", function (e) {

        const nextImage = get_next_image(image.imageId);
        const prevImage = get_previous_image(image.imageId);

        deleteImage(image.imageId);

        if (nextImage) {
            loadImage(nextImage);
        } else if (prevImage) {
            loadImage(prevImage);
        } else {
            document.getElementById("image_sec").innerHTML = ``;
            document.getElementById("messages").innerHTML = ``;
        }
    });

    document.getElementById("add_comment").addEventListener("click", function (e) {
        const comment_author = document.getElementById("comment_name").value;
        const comment = document.getElementById("comment").value;

        addComment(image.imageId, comment_author, comment);

        document.getElementById("comment_form").reset();

        loadLatestComments(image.imageId);

    });

    loadLatestComments(image.imageId);
}

